In [3]:
x = [[1., 0., 0.], [0., 1., 2.]]
type(x)

list

In [5]:
import numpy as np

a=np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
type(a)

numpy.ndarray

In [8]:
#Dizinin boyutlarını verir
a.shape

(3, 5)

In [10]:
#Dizinin kaç boyutlu olduğunu syler dizi tek stndan oluşsaydı 1 sonucunu alacaktık
a.ndim

2

In [11]:
#dizinin içeriğinin hangi formatta olduğunu sylüyor
a.dtype.name

'int32'

In [13]:
#dizinin boyutunu gsterir
a.size

15

In [15]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [16]:
type(b)

numpy.ndarray

In [17]:
b.ndim

1

***Array creation***

In [19]:
import numpy as np

a = np.array([2, 3, 4])

b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [22]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.empty((5,6))

array([[7.39993968e-312, 1.02271589e-321, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307, 5.02034658e+175],
       [2.10682285e-076, 5.94195929e-038, 8.45364699e+169,
        1.83221714e-076, 9.83253170e-072, 4.26125772e-096],
       [1.12855837e+277, 8.76730979e+252, 2.59027920e-144,
        3.80985069e+180, 1.14428494e+243, 2.59027907e-144],
       [7.79952704e-143, 9.34063434e+164, 2.52701365e-052,
        1.60470285e-051, 1.10898771e-047, 2.59027903e-144],
       [2.59903818e-144, 6.19410690e-091, 1.38401623e-047,
        4.76076549e-038, 1.11475752e+261, 1.16318408e-028]])

In [27]:
#10 dan 30 a kadar 5 er arttırararak array oluştur
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [29]:
#aynı islemi float degerlerdede yapabiliyoruz
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [32]:
from numpy import pi
#0 dan 1 e 9 tane sayı
np.linspace(0,2,9)

x = np.linspace(0,2 * pi, 100)
f = np.sin(x)
x,f

(array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
        0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
        0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
        0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
        1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
        1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
        1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
        2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
        2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
        2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
        3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
        3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
        3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
        4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
        4.44265628, 4.5061228 , 4.56958931, 4.63

***Printing Arrays***

In [35]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [37]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
#3d array
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])